config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :companies, path: :company do
    member do
      devise_for :users, only: [:registrations], :controllers => { registrations: 'registrations' }, path_names: {sign_up: 'register'}
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
    validates :company_reg, uniqueness: {scope: :country}
    validates_presence_of :company_name, :industry, :country, :company_reg, :contact_person, :contact_num

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

    def new
        @company = Company.new
    end

    def create
        @company = Company.create(company_params)
        if @company.save
            flash[:success] = "Company created"
            redirect_to company_path(@company)
        else
            flash[:error] = "Failed to create company"
            # redirect_back(fallback_location: root_path)
            render 'new'
        end
    end

    def show
        @company = Company.find(params[:id])
    end

    private

    def company_params
        params.require(:company).permit(:company_name, :industry, :country, :company_reg, :contact_person, :contact_num)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def new
        @company = Company.find(params[:id])
        build_resource
        yield resource if block_given?
        respond_with resource
    end

    def create
        @company = Company.find(params[:id])
        build_resource(sign_up_params)
        resource.company_id = params[:id]
        resource.save
        yield resource if block_given?
        if resource.persisted?
          if resource.active_for_authentication?
            set_flash_message! :notice, :signed_up
            sign_up(resource_name, resource)
            respond_with resource, location: after_sign_up_path_for(resource)
          else
            set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
            expire_data_after_sign_in!
            respond_with resource, location: after_inactive_sign_up_path_for(resource)
          end
        else
          clean_up_passwords resource
          set_minimum_password_length
          respond_with resource
        end
      end


    protected
    def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/companies/_error_messages.html.erb
<% if @company.errors.any? %>
    <% @company.errors.full_messages.each do |messages| %>
        <li> <%= messages %> </li>
    <% end %>
<% end %>

app/views/companies/new.html.erb
<h1>Create New Company</h1>

<%= form_with url: companies_path, scope: :company, local: true do |form| %>
    <% if @company.errors.any? %>
        <p><%= pluralize(@company.errors.count,"error") %> found:
        <% @company.errors.full_messages.each do |messages| %>
            <p><%= messages %></p>
        <% end %>
    <% end %>
    
    <p>
        Company Name: 
        <%= form.text_field :company_name %>
    </p>
    <p>
        Industry:<%= form.text_field :industry %>
    </p>    
    <p>
        Country:<%= form.text_field :country %>
    </p>    
    <p>
        Business Registration No.:<%= form.text_field :company_reg %>
    </p>    
    <p>
        Contact Person :<%= form.text_field :contact_person %>
    </p>    
    <p>
        Contact Number :<%= form.text_field :contact_num %>
    </p>    
    <p>
        <%= form.submit %>
    </p>
<% end %>

app/views/companies/show.html.erb
<h1>Company Profile ---------- <%= @company.company_name %></h1>

app/views/home/index.html.erb
<h1>This is the home page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniCMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= "#{key} : #{value}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>